### ISSUE TITLE
Issue with requirements.txt

### ISSUE THREAD

**Issue by aaronuv** [brendenpetersen/deep-symbolic-regression#11]
Hi, I traid to install the package, but at the requirements.txt stage, the following issue appears:

`Collecting pytest (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/a1/cf/7f67585bd2fc0359ec482cf3c430bce3ef6d3f40bc468137225a733e3069/pytest-6.2.2-py3-none-any.whl
Collecting cython (from -r requirements.txt (line 2))
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/19/49/91ebe4a00bf894d08dd9680cd9dfb05936eb2848eebd9402b43885aa74cf/Cython-0.29.21-cp36-cp36m-manylinux1_x86_64.whl
Collecting numpy (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/45/b2/6c7545bb7a38754d63048c7696804a0d947328125d81bf12beaa692c3ae3/numpy-1.19.5-cp36-cp36m-manylinux1_x86_64.whl
Collecting tensorflow==1.14 (from -r requirements.txt (line 4))
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/de/f0/96fb2e0412ae9692dbf400e5b04432885f677ad6241c088ccc5fe7724d69/tensorflow-1.14.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting numba (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/46/e1/cbbc7c7967d9b10e54c852bf5bece0222a63bfb809d3354014c957ef1bda/numba-0.52.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/home/aaron/deep-symbolic-regression/venv3/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/aaron/deep-symbolic-regression/venv3/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/aaron/deep-symbolic-regression/venv3/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/aaron/deep-symbolic-regression/venv3/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-i90e2pu4/numpy-1.20.0/setup.py", line 30, in <module>
        # Patch for #2555 to make wheels without libpython
    RuntimeError: Python version >= 3.7 required.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-b2ynfpb2/numba/setup.py", line 415, in <module>
        setup(**metadata)
      File "/home/aaron/deep-symbolic-regression/venv3/lib/python3.6/site-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/home/aaron/deep-symbolic-regression/venv3/lib/python3.6/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/aaron/deep-symbolic-regression/venv3/lib/python3.6/site-packages/setuptools/dist.py", line 513, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/aaron/deep-symbolic-regression/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
        replace_conflicting=replace_conflicting
      File "/home/aaron/deep-symbolic-regression/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1057, in best_match
        return self.obtain(req, installer)
      File "/home/aaron/deep-symbolic-regression/venv3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1069, in obtain
        return installer(requirement)
      File "/home/aaron/deep-symbolic-regression/venv3/lib/python3.6/site-packages/setuptools/dist.py", line 580, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/aaron/deep-symbolic-regression/venv3/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 698, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/aaron/deep-symbolic-regression/venv3/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 724, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/aaron/deep-symbolic-regression/venv3/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 909, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/aaron/deep-symbolic-regression/venv3/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1177, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/aaron/deep-symbolic-regression/venv3/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1163, in run_setup
        run_setup(setup_script, args)
      File "/home/aaron/deep-symbolic-regression/venv3/lib/python3.6/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/aaron/deep-symbolic-regression/venv3/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/aaron/deep-symbolic-regression/venv3/lib/python3.6/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/home/aaron/deep-symbolic-regression/venv3/lib/python3.6/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/home/aaron/deep-symbolic-regression/venv3/lib/python3.6/site-packages/setuptools/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/home/aaron/deep-symbolic-regression/venv3/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/aaron/deep-symbolic-regression/venv3/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/aaron/deep-symbolic-regression/venv3/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/aaron/deep-symbolic-regression/venv3/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-i90e2pu4/numpy-1.20.0/setup.py", line 30, in <module>
        # Patch for #2555 to make wheels without libpython
    RuntimeError: Python version >= 3.7 required.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-b2ynfpb2/numba/
`

I tried to remove the TensorFlow version from it, but still didn't work.

**Comment by brendenpetersen** [comment]
Unfortunately I can’t reproduce this. Can you try installing each component separately instead of all at once via requirements.txt? Sometimes numpy likes to be installed before other packages, for example.

**Comment by aaronuv** [comment]
It seems that the problem is in the llvmlite package. I will close the issue, thanks.
