### ISSUE TITLE
Terminal is not defined

### ISSUE THREAD

**Issue by zodiac911** [brendenpetersen/deep-symbolic-regression#2]
> when I run run_Constant_gp.sh as instructed, I got the following error

(dsr) ➜  paper git:(master) ./run_Constant_gp.sh 
Setting 'num_cores' to 30 for batch because there are only 30 expressions.
Running gp for n=10 on benchmarks ['Constant-1', 'Constant-2', 'Constant-3']
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/wangtao/opt/anaconda3/envs/dsr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/wangtao/MY_FILES/deep-symbolic-regression/dsr/dsr/run.py", line 89, in train_gp
    p, logbook = gp.train()
  File "/Users/wangtao/MY_FILES/deep-symbolic-regression/dsr/dsr/baselines/gpsr.py", line 176, in train
    verbose=self.verbose)
  File "/Users/wangtao/opt/anaconda3/envs/dsr/lib/python3.6/site-packages/deap/algorithms.py", line 151, in eaSimple
    for ind, fit in zip(invalid_ind, fitnesses):
  File "/Users/wangtao/MY_FILES/deep-symbolic-regression/dsr/dsr/baselines/gpsr.py", line 141, in evaluate
    optimized_consts = self.const_opt(obj, x0)
  File "/Users/wangtao/MY_FILES/deep-symbolic-regression/dsr/dsr/const.py", line 72, in __call__
    opt_result = partial(minimize, **self.kwargs)(f, x0)
  File "/Users/wangtao/opt/anaconda3/envs/dsr/lib/python3.6/site-packages/scipy/optimize/_minimize.py", line 604, in minimize
    return _minimize_bfgs(fun, x0, args, jac, callback, **options)
  File "/Users/wangtao/opt/anaconda3/envs/dsr/lib/python3.6/site-packages/scipy/optimize/optimize.py", line 1003, in _minimize_bfgs
    old_fval = f(x0)
  File "/Users/wangtao/opt/anaconda3/envs/dsr/lib/python3.6/site-packages/scipy/optimize/optimize.py", line 327, in function_wrapper
    return function(*(wrapper_args + args))
  File "/Users/wangtao/MY_FILES/deep-symbolic-regression/dsr/dsr/baselines/gpsr.py", line 132, in obj
    individual[i] = Terminal(const, False, object)
NameError: name 'Terminal' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/wangtao/opt/anaconda3/envs/dsr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/wangtao/opt/anaconda3/envs/dsr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/wangtao/MY_FILES/deep-symbolic-regression/dsr/dsr/run.py", line 252, in <module>
    main()
  File "/Users/wangtao/opt/anaconda3/envs/dsr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/wangtao/opt/anaconda3/envs/dsr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/wangtao/opt/anaconda3/envs/dsr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/wangtao/opt/anaconda3/envs/dsr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/wangtao/MY_FILES/deep-symbolic-regression/dsr/dsr/run.py", line 242, in main
    for result in pool.imap_unordered(work, names_and_seeds):
  File "/Users/wangtao/opt/anaconda3/envs/dsr/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
NameError: name 'Terminal' is not defined

real	0m2.246s
user	0m2.755s
sys	0m1.022s

**Comment by brendenpetersen** [comment]
Thanks for pointing this out! I just pushed a fix. Just had to replace `Terminal` with `gp.Terminal`.
